---

- name: Install Python packages
  become: true
  apt:
    pkg: ["python3", "python3-dev", "python3-pip", "python3-venv", "python3-tk"]
    state: latest
    update_cache: yes
    cache_valid_time: "{{ aptcachetime }}"
