- name: Add key
  apt_key:
    url: "https://nvidia.github.io/libnvidia-container/gpgkey"
    state: present

- name: Add package repo
  get_url:
    url: https://nvidia.github.io/libnvidia-container/stable/deb/nvidia-container-toolkit.list
    dest: /etc/apt/sources.list.d/nvidia-container-toolkit.list
    mode: 0644
    owner: root
    group: root

- name: Install container toolkit
  apt:
    name: nvidia-container-toolkit
    state: present
    update_cache: true

- name: Configure docker
  shell: nvidia-ctk runtime configure --runtime=docker

- name: Restart docker deamon
  service:
    name: docker
    state: restarted

