---
- name: Install CUDA on nodes with GPUs
  hosts: all
  become: true
  gather_facts: true
  pre_tasks:
  - name: Check which nodes have NVIDIA GPUs
    register: lspci_result
    changed_when: false
    check_mode: false
    ansible.builtin.command:
      cmd: "lspci"

  tasks:
  - name: Install CUDA
    vars:
      driver_version: propriety
    when: lspci_result['stdout'] | regex_search('vga.*nvidia', ignorecase=true, multiline=false)
    ansible.builtin.include_role:
      name: install_nvidia_cuda


# ansible-galaxy role install andrewtwin.install_nvidia_cuda
